### ISSUE TITLE
[Question] : Setup multiple life cycle configurations with the same instance

### ISSUE THREAD

**Issue by vatsal102** [aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples#106]
Is there a way to setup multiple life cycle configurations associated with the same instance? I was to combine two configs, the auto-stop-idle script and another which installs a bunch of packages upon starting the instance.

**Comment by tayodok** [comment]
you can add all the script contents to a single LCC. currently notebooks do not allow attachment of multiple LCCs.
