### ISSUE TITLE
Following env variable example has Jupyter return 500 code

### ISSUE THREAD

**Issue by anthonydandrea** [aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples#113]
I followed the example script for setting environment variables and then reloading jupyter within the Lifecycle Configuration scripts: https://github.com/aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples/blob/master/scripts/set-env-variable/on-start.sh

However, when I do this and go to open my notebook, I receive `500 : Internal Server Error` in the notebook session.

**Comment by tayodok** [comment]
Hi. Which platform version are you using for your notebook?

**Comment by anthonydandrea** [comment]
Amazon Linux 2, Jupyter Lab 3
(notebook-al2-v2)

**Comment by dmlause** [comment]
Hi @anthonydandrea - are you still seeing this issue? If so, please check the Jupyter logs in Cloudwatch of the owning AWS account, along with any errors in the lifecycle configuration script Cloudwatch logs as well. What environment variables are you setting in this script? If we don't hear back soon, I will close this issue for inactivity, thank you.
