### ISSUE TITLE
Sessionless notebook instance is idle?

### ISSUE THREAD

**Issue by jaisojar** [aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples#16]
Hi,

I noticed something funny when trying to use this on-start script on one of our notebook instances: https://github.com/aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples/blob/4f7fece1143041d0bacf3ef9f8e03fc261a724cd/scripts/auto-stop-idle/autostop.py#L102

The code seems to indicate, that a notebook instance without any active sessions is not idle. This does not seem right to me, maybe I am missing something?

**Comment by jmgray24** [comment]
Addressed in #17.
