### ISSUE TITLE
source activate

### ISSUE THREAD

**Issue by predictedblog** [aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples#20]
Hey there,

it cost me a lot of time to figure out that using 
`source activate ... (e.g. pytorch_p36)`
is working and
`source /home/ec2-user/anaconda3/bin/activate ... (e.g. pytorch_p36) `
is not.
Maybe change the code in "install-pip-package-single-environment" accordingly.

**Comment by Lstilwell** [comment]
Hey there! 

Could you further explain what you mean by "working" and "not working"? I'm able to use `source /home/ec2-user/anaconda3/bin/activate` without any problems.

**Comment by predictedblog** [comment]
Hey, never mind it's working with `source /home/ec2-user/anaconda3/bin/activate` now.
