### ISSUE TITLE
set-env-variable do not evaluate YOUR_ENV_VARIABLE_NAME properly

### ISSUE THREAD

**Issue by PedroMBPinheiro** [aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples#23]
I have tried the set-env-variable script but it returns a string empty for YOUR_ENV_VARIABLE_NAME when evaluating the line

DO NOT WORK
YOUR_ENV_VARIABLE_NAME=tagkey
TAG=$(aws sagemaker list-tags --resource-arn $NOTEBOOK_ARN  | jq .'Tags[] | select(.Key == "$YOUR_ENV_VARIABLE_NAME").Value' --raw-output)

It seems that for some reason the $YOUR_ENV_VARIABLE_NAME is not substituted by the value due to being enclosed in "".

But if I replace the YOUR_ENV_VARIABLE_NAME with the actual string then works. But I would prefer not to hardcode the KEY in the script.

WORKS
TAG=$(aws sagemaker list-tags --resource-arn $NOTEBOOK_ARN  | jq .'Tags[] | select(.Key == "tagkey").Value' --raw-output)

**Comment by Lstilwell** [comment]
Hi there! Thank you for using Amazon SageMaker!  Thanks for noticing this. We'll work on getting a fix out for this soon. In the meantime, you can use the jq --arg flag to pass in the variable like so:

```
TAG=$(aws sagemaker list-tags --resource-arn $NOTEBOOK_ARN  | jq -r --arg YOUR_ENV_VARIABLE_NAME "$YOUR_ENV_VARIABLE_NAME" .'Tags[] | select(.Key == $YOUR_ENV_VARIABLE_NAME).Value' --raw-output)
```

**Comment by neelamgehlot** [comment]
Closing the issue since the fix has been merged. 

@PedroMBPinheiro Please re-open if you still see the issue.
