### ISSUE TITLE
SageMaker notebook instance doesn't work with ipywebrtc extension

### ISSUE THREAD

**Issue by ThomasDelteil** [aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples#24]
This extension doesn't work on SageMaker https://github.com/maartenbreddels/ipywebrtc
I suspect this could be due to how the proxy is setup:
I get this error in the inspector:

`The resource from “https://XXXXXXXX.notebook.us-east-2.sagemaker.aws/static/jupyter-webrtc.js?v=20191125191846” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff`

Any idea how to make it work?

`pip install ipywebrtc`

```
from ipywebrtc import CameraStream, ImageRecorder
camera = CameraStream(constraints=
                      {'facing_mode': 'user',
                       'audio': False,
                       'video': { 'width': 640, 'height': 480 }
                       })
camera
```

**Comment by dmlause** [comment]
Is this still an issue for you?
