### ISSUE TITLE
Script fails with "ArgumentError: Argument --name requires a value" error

### ISSUE THREAD

**Issue by shariefyoussef** [aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples#28]
When this script is run as a Lifecycle configuration for a SageMaker Notebook Instance, it fails.

CloudWatch has this error logged: "ArgumentError: Argument --name requires a value"

The Notebook Instance eventually fails to start due to timeout.

**Comment by mckev-amazon** [comment]
Resolving, thank you for the PR and for reporting this issue!
