### ISSUE TITLE
why use pip

### ISSUE THREAD

**Issue by bastia1989** [aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples#30]
why use pip in conda environment rather than conda install?

Another problem, if you use conda install, that may take more than 5 mins. can you use `nohup` to solve the time-ran-out issue? If you could, how we should do that?

**Comment by dleen** [comment]
Hi,

An example of how to use `nohup` to run the install in the background can be found here:

https://github.com/aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples/blob/3ddb1dcf0c58a0c7e176f27827dbe3bf7f22c22f/scripts/install-conda-package-all-environments/on-start.sh#L10

**Comment by jaipreet-s** [comment]
Hi @bastia1989 ,

I'm going to resolve this issue as @dleen has responded. Please let us know if there's anything else required!
