### ISSUE TITLE
Extension install scripts fail with empty variables

### ISSUE THREAD

**Issue by athewsey** [aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples#32]
The `sudo -u ec2-user -i EOF` pattern used in the [install-lab-extension](https://github.com/aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples/blob/master/scripts/install-lab-extension/on-start.sh) sample fails because the main shell resolves the variable `$EXTENSION_NAME` (to blank) before it's passed to the subshell in the script.

As noted [here](https://riptutorial.com/bash/example/16898/run-several-commands-with-sudo), we need to escape $ when using this pattern.

I have a PR ready to fix this for both the [install-lab-extension](https://github.com/aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples/blob/master/scripts/install-lab-extension/on-start.sh) and [install-nb-extension](https://github.com/aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples/blob/master/scripts/install-nb-extension/on-start.sh) samples - will submit after recording the issue.

...but I think this might affect other samples too?

**Comment by athewsey** [comment]
I just did a quick check and think this will also affect:

- [install-conda-package-all-environments](https://github.com/aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples/blob/master/scripts/install-conda-package-all-environments/on-start.sh)
- [install-conda-package-single-environment](https://github.com/aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples/blob/master/scripts/install-conda-package-single-environment/on-start.sh)
- [install-pip-package-all-environments](https://github.com/aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples/blob/master/scripts/install-pip-package-all-environments/on-start.sh)
- [install-pip-package-single-environment](https://github.com/aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples/tree/master/scripts/install-pip-package-single-environment)
- [install-server-extension](https://github.com/aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples/blob/master/scripts/install-server-extension/on-start.sh)
- [persistent-conda-ebs](https://github.com/aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples/blob/master/scripts/set-git-config/on-start.sh)
- [set-git-config](https://github.com/aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples/blob/master/scripts/set-git-config/on-start.sh)

**Comment by mckev-amazon** [comment]
Hi athewsey,

Thanks for submitting this issue.  Indeed, it would appear that we need to quote the "heredoc delimiter" with quotes in order to disable variable expansion entirely inside of the heredoc.  Escaping $ with \$ would also work as well (no strong preference to either).

Feel free to submit a PR for the others, otherwise we will fix this as soon as possible.

**Comment by athewsey** [comment]
I agree that, for the majority of our scripts that don't take any params from the parent shell, quoting the heredoc delimiter is more readable/less overhead than escaping each use of a variable :-)

Will raise a PR imminently to have a crack at the rest and revert the extension installation ones to quoted delimiter

**Comment by mckev-amazon** [comment]
Awesome, thank you very much!
