### ISSUE TITLE
Example script fails "auto_stop_idle.sh" - crontab

### ISSUE THREAD

**Issue by AurelienMassiot** [aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples#40]
Hello,
I am launching a Sagemaker instance using Terraform. I attached it a lifecycle configuration including the file _auto_stop_idle.sh_ so that it stops when idle.

I have managed to attach it but I think the crontab line in the bash file is incorrect:
`(crontab -l 2>/dev/null; echo "5 * * * * /usr/bin/python $PWD/autostop.py --time $IDLE_TIME --ignore-connections") | crontab -` (**does nothing**)

should be:
`(crontab -l 2>/dev/null; echo "*/5 * * * * /usr/bin/python $PWD/autostop.py --time $IDLE_TIME --ignore-connections") | crontab -` (**works**)

Should I consider making a PR ?

**Comment by RokoMijic** [comment]
`5 * * * * `tells cron to run the python script at 5 minutes past the hour, so your notebook can only shut down at XX:05. 

`*/5 * * * *` tells cron to run it every 5 minutes. 

I think the latter is more appropriate, so yes you should submit a Pull Request.

**Comment by AurelienMassiot** [comment]
Done, PR #42.

**Comment by neelamgehlot** [comment]
Merged PR #42
