### ISSUE TITLE
LifeCycle Configurations for R kernel: install R packages

### ISSUE THREAD

**Issue by MiguelSotelo2** [aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples#43]
Good afternoon
I have a question regarding the problem posted [here](https://github.com/awslabs/amazon-sagemaker-examples/issues/320)

The standard R kernel when making a SageMaker notebook instance from Jupyter does not have some packages I would like installed. Manually installing them (`R: install.packages("rjson")`) takes a very long time. Some of the packages I want to install are 'rstan', 'survival', 'tidyverse'.

I would like to create a Lifecycle configurations script that automatically installs these packages when creating a notebook instance.

My current configurations file is:
`#!/bin/bash`
`sudo -u ec2-user -i <<'EOF'`
`conda install --yes --name R --channel r r-essentials=3.6.0`
`EOF`
After creating the notebook instance and starting a new notebook (R-kernel), I run 
`("rjson" %in% installed.packages())`
`("r-rjson" %in% installed.packages())`
To test whether _at the very least_ rjson is installed. However, it is not

**Any help in getting my configurations script would be appreciated!!**

Edit: I want a functionality like [this](https://github.com/aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples/tree/master/scripts/persistent-conda-ebs)

**Comment by urirosenberg** [comment]
Added pull request #57 to solve this.

**Comment by urirosenberg** [comment]
r example added.  Please see [here](https://github.com/aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples/tree/master/scripts/install-r-package).
Hope this helps!

**Comment by jaipreet-s** [comment]
thanks @urirosenberg. Closing this sim as #57 resolves this.
