### ISSUE TITLE
persistent-conda-ebs/on-start.sh does not add multiple conda environments

### ISSUE THREAD

**Issue by hbrumley** [aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples#47]
When I create multiple conda environments in the custom-miniconda folder the script only correctly adds one as a Jupyter kernel.

I traced the problem to line 23. After the first iteration of the for loop the log prints "Could not find conda environment: [my environment name]"

Changing line 23 from ```source activate "$BASENAME"``` to ```conda activate $BASENAME``` solves the problem for me.

**Comment by dmlause** [comment]
I was unable to reproduce this issue and I was able to successfully activate a conda environment by running `source activate env` , closing
