### ISSUE TITLE
Python kernels are not available after running the lifecycle config

### ISSUE THREAD

**Issue by marklaszlo9** [aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples#51]
I am using the following lifecycle config:
ENVIRONMENT=python3
NOTEBOOK_FILE=/home/ec2-user/SageMaker/data_prep.ipynb

source /home/ec2-user/anaconda3/bin/activate "$ENVIRONMENT"

nohup jupyter nbconvert "$NOTEBOOK_FILE" --ExecutePreprocessor.kernel_name=python --ExecutePreprocessor.timeout=1500 --execute &

source /home/ec2-user/anaconda3/bin/deactivate
It runs smoothly, however when I open up the notebook only R and Sparkmagic kernels are available, so I can not edit my data_prep.ipynb. It started about a week ago. Has anyone experienced similar behaviour?
Cheers, Mark

**Comment by furkandoganktf** [comment]
Any update on this ?

**Comment by cvargas-geo** [comment]
In my case the R kernel is not recognised by default 

[R START UP LCC](https://github.com/aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples/blob/master/scripts/execute-notebook-on-startup/on-start.sh)

**Comment by cvargas-geo** [comment]
for the kernel conda_python  it throws me the stge error 

`jupyter_client.kernelspec.NoSuchKernel: No such kernel named conda_python3`

LCC

`#!/bin/bash
set -eux
#init in /home/ec2-user
nohup sudo -b -u ec2-user -i <<'EOF' 
echo $PWD  
conda activate R 
conda install 'r-sp' -y  --name 'R' 

# EJECUCION AUTOMATICA D NOTEBOOKS
ENVIRONMENT=R
FILE0="/home/ec2-user/SageMaker/00_setup.ipynb"
FILE1="/home/ec2-user/SageMaker/01_oultiers_oi.ipynb"
FILE2="/home/ec2-user/SageMaker/02_outliers_avaluo.ipynb"
FILE3="/home/ec2-user/SageMaker/03_outliers_cbr_final.ipynb"
FILE4="/home/ec2-user/SageMaker/04_generacion_capa_ufm2.ipynb"
conda activate JupyterSystemEnv

nohup jupyter nbconvert "$FILE0"  --execute --to notebook  --ExecutePreprocessor.timeout=300
#jupyter nbconvert "$NOTEBOOK_FILE"  --execute --to notebook  
conda deactivate

# PARAMETERS
IDLE_TIME=60

echo "Fetching the autostop script"
wget https://raw.githubusercontent.com/aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples/master/scripts/auto-stop-idle/autostop.py

echo "Starting the SageMaker autostop script in cron"

(crontab -l 2>/dev/null; echo "*/1 * * * * /usr/bin/python $PWD/autostop.py --time $IDLE_TIME  ") | crontab -
#(crontab -l 2>/dev/null; echo "*/1 * * * * /usr/bin/python $PWD/autostop.py --time $IDLE_TIME --ignore-connections") | crontab -
 
EOF`

**Comment by dmlause** [comment]
Hello @marklaszlo9 , is this still an issue for you? It has been a very long time since this issue was opened, so I would like to clarify if a problem still exists. If I don't hear back soon, I will close this issue for inactivity. Thank you.

**Comment by marklaszlo9** [comment]
Hi @dmlause , you may close this. Thanks
