### ISSUE TITLE
[Request] sample for installing packages to Python3+ environments only

### ISSUE THREAD

**Issue by athewsey** [aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples#55]
Many packages today don't provide backward compatibility to Python v2, so samples like `install-pip-package-all-environments` are useful but can require a non-trivial workaround to ignore Py2 environments.

I think I have a working example of this already (with `smdebug` and `sagemaker-experiments`), so will raise a PR to accompany this issue.

**Comment by dmlause** [comment]
Python 2 is no longer supported for notebook instances, see https://docs.aws.amazon.com/sagemaker/latest/dg/nbi-jl.html . Closing this issue, thank you.
