### ISSUE TITLE
Increase sagemaker notebook instance session duration

### ISSUE THREAD

**Issue by shubhamsharma1609** [aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples#58]
I have a large training job, I am training using keras on ml.p2.xlarge instance and using conda_amazonei_tensorflow_p36 notebook. I got to know that juoyter notebook session duration lasts for 12 hours but my training job will take more than that. Can I increase the duration ?If so,how.

**Comment by Ghoul-SSZ** [comment]
I can think of 3 ways:
1. Write the python code using nohup
2. Change the notebook instance to p3.2xlarge to speed up the training time
3. Use sagemaker training, but probably you need to build a docker img first. but its the most cost effective way think

**Comment by dmlause** [comment]
@shubhamsharma1609 - The suggestions provided by @Ghoul-SSZ are correct, and I would suggest investigating other solutions to run your training jobs in a distrubuted and/or asynchronous manner. I am closing this issue. Please open a new issue if one still exists, thank you.
