### ISSUE TITLE
tensorflow_p36 environment running notebook fails through configuration

### ISSUE THREAD

**Issue by ahiranandani** [aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples#61]
Trying to run a Sagemaker notebook that essentially runs inference for a Keras language model.
The notebook works well standalone but doesn't work with the notebook lifecycle instance configuration. 

The notebook should run in the tensorflow_p36 virtual environment and the conda_tensorflow_p36 kernel.

My file looks like this:

set -e

NOTEBOOK_FILE="/home/ec2-user/SageMaker/notebook.ipynb"
ENVIRONMENT="tensorflow_p36"
AUTO_STOP_FILE="/home/ec2-user/SageMaker/auto-stop.py"

source /home/ec2-user/anaconda3/bin/activate "$ENVIRONMENT"

nohup jupyter nbconvert --ExecutePreprocessor.kernel_name=conda_tensorflow_p36 --execute "$NOTEBOOK_FILE" &

source /home/ec2-user/anaconda3/bin/deactivate
IDLE_TIME=60

echo "Fetching the autostop script"
wget https://raw.githubusercontent.com/aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples/master/scripts/auto-stop-idle/autostop.py

echo "Starting the SageMaker autostop script in cron"
(crontab -l 2>/dev/null; echo "*/1 * * * * /usr/bin/python $PWD/autostop.py --time $IDLE_TIME --ignore-connections") | crontab -

The error message from CloudWatch logs is:
cp: cannot stat '/root/.keras/keras_tensorflow.json': No such file or directory

Any fix?

**Comment by AlexSchumi** [comment]
Hey there, have you figured out the issue, I have similar one when activating the mxnet_latest_p37 environment.

**Comment by JoanWu5** [comment]
I also encounter the same issue facing mxnet_p36
From terminal: `source "/home/ec2-user/anaconda3/bin/activate" mxnet_p36`
can succeed, however, when I put this to lifecycle configuration,
it throws out error:` cp: cannot stat '/root/.keras/keras_mxnet.json': No such file or directory`

**Comment by dmlause** [comment]
Hello @ahiranandani - these kernels are not available on SageMaker Notebook Instances as of writing, see https://docs.aws.amazon.com/sagemaker/latest/dg/nbi-al2.html#nbi-al2-kernel and please let us know if you are still having issues. If we don't hear back soon, I will close this issue for inactivity. Thank you.
