### ISSUE TITLE
Not able to launch a default kernel

### ISSUE THREAD

**Issue by sauravjoshi** [aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples#62]
Hi All,

I'm programatically creating the sagemaker notebook instance, and wanted that any new notebook should open by default with a python3 kernel, however when I open up a notebook **Could not find a kernel matching Python 3** , occurs giving a prompt to chose from the available kernels.

I searched online and tried out making additions to the jupyter_notebook_config.py in lifecycle scripts inside /home/ec2-user/.jupyter as 
```
c.MultiKernelManager.default_kernel_name = 'python3', also tried
c.MultiKernelManager.default_kernel_name = 'conda-env-python3-py'
```
Noone of which seem to work.
How to solve this i.e. instead of asking for a prompt, directly loading the notebook with the said kernal. Also I noticed that this is particularly for the newly created instances, an instance that is stopped and restarted doesn't face this. Peculiar? 

Thanks

**Comment by micah5** [comment]
Just add
```bash
sudo -u ec2-user -i <<'EOF'

python -m ipykernel install --user --name python3 --display-name python3

EOF
```

to the lifecycle start script. It'll take the default python environment and add it as a new kernel called `python3` (which is what jupyter is looking for by default).

**Comment by dmlause** [comment]
Hi @sauravjoshi - your original comment is correct that you should modify the Jupyter config for your default kernel, however, you likely need to restart the Jupyter service itself, see https://github.com/aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples/blob/master/scripts/set-env-variable/on-start.sh#L27 for example.

Let us know if this resolves your issue, or if you still have an issue. If we don't hear back soon, I will close this issue for inactivity. Thanks!

**Comment by sauravjoshi** [comment]
Thanks for the comments.
