### ISSUE TITLE
notebook-history-s3 cronjob not saving data to S3 

### ISSUE THREAD

**Issue by jendoubizaid** [aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples#63]
The on-start.sh script is downloading a file named "**notebook-history-s3.py**" using the following command:
 `wget https://raw.githubusercontent.com/aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples/master/scripts/notebook-history-s3/notebook-history-s3.py`

But, when it creates a cronjob, it tries to execute a python file named "**notebook_history_s3.py**" which doesn't exist.
`(crontab -l 2>/dev/null; echo "0 * * * * /usr/bin/python3 $PWD/notebook_history_s3.py") | crontab -`

suggested change to fix the issue:
`(crontab -l 2>/dev/null; echo "0 * * * * /usr/bin/python3 $PWD/notebook-history-s3.py") | crontab -`

**Comment by dmlause** [comment]
Thank you for pointing this out. We will work on resolving this in an upcoming PR.

**Comment by dmlause** [comment]
The PR above has been merged, thank you for pointing out this issue. Closing this since it is resolved.
