### ISSUE TITLE
Notebook instance keeps refreshing the page without opening Jupyter(Lab)

### ISSUE THREAD

**Issue by annisall** [aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples#65]
I have a Sagemaker notebook instance created with TypeScipt CDK, and I also created a lifecycle rule for it. I used [auto-stop-idle](https://github.com/aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples/tree/master/scripts/auto-stop-idle) example to create the script and ensured it is working. In on-start.sh script I get a [specific version of the python script](https://raw.githubusercontent.com/aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples/4635c50c7abed8c8b3cb6afe5234f9206e191714/scripts/auto-stop-idle/autostop.py) in the example to make sure we know which version we're using on start. 

Stopping the instance after it's been idle for an hour worked just fine, but I started experiencing a problem that once I started the instance again, and tried to open jupyter / jupterlab, it would get stuck and keep refreshing the page. I contacted AWS support about the issue, and they were able to reproduce the problem. They noticed that it doesn't happen every time, though.

They suggested following things:
1. Retry starting your Notebook instances, and wait for a few minutes even though the Jupyter interface seems stuck in refreshing the loading page.

2. If the issue persists, try to clear your browser cache or try on a different browser. 

3. Again, if Jupyter interface isn’t opening, please stop the notebook instance, remove its auto-stop-idle lifecycle configuration, re-try to start and open it, and let me know if the issue still happens on the instance without lifecycle policy.

4. Kindly share the `jupyter.log` file with me:
    1) Go to SageMaker console and choose notebook instances.
    2) Open the notebook instance in which you are facing this issue.
    3) Under ‘Monitor’ section, select ‘View logs’. It will redirect you to CloudWatch logs.
    4) In the CloudWatch console, choose the log stream for your notebook instance. Its name is in the form <NotebookInstanceName>/jupyter.log.
    5) You can download the logs from CloudWatch by selecting ‘Actions’ -> ‘Download as .CSV file’.

and the second one helped me. So clearing cookies / using incognito mode on Chrome resolved the issue. We haven't had this problem before, before we started using the lifecycle rule mentioned.

If you need any additional details from me, please let me know.

**Comment by dmlause** [comment]
Hello @annisall - is there still an issue here? If there is no response soon, I will close this issue for inactivity. Thank you.
