### ISSUE TITLE
lifecycle config R libraries from both CRAN and Bioconductor

### ISSUE THREAD

**Issue by aGutierrezSacristan** [aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples#66]
Any suggestion/tips about how to have Bioconductor libraries pre-installed in SageMaker?
The lifecycle configuration script to have pre-installed R libraries is only working for me for CRAN R libraries:

`#!/bin/bash
set -e
nohup sudo -b -u ec2-user -i <<'EOF'
conda install "r-ggplot2" --name "R" --yes
conda install "r-rentrez" --name "R" --yes
EOF`

But when I add R libraries from Bioconductor, those are not installed. For example the next script will successfully install rentrez and ggplot2 (CRAN libraries) but not oligo nor annotate (Bioconductor libraries) :

`#!/bin/bash
set -e
nohup sudo -b -u ec2-user -i <<'EOF'
conda install "r-rentrez" --name "R" --yes
conda install "r-oligo" --name "R" --yes
conda install "r-annotate" --name "R" --yes
conda install "r-ggplot2" --name "R" --yes
EOF`

Any idea how to make it work?

**Comment by dmlause** [comment]
Hello @aGutierrezSacristan - are you still seeing this issue? I would recommend ensuring the Bioconductor R repository is enabled via a lifecycle configuration script update and then attempt to download those packages. If we do not hear back soon, I will close this issue for inactivity, thank you.
