### ISSUE TITLE
Add IMDS service IP to NO_PROXY list in proxy-for-jupyter

### ISSUE THREAD

**Issue by dfkunstler** [aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples#68]
The IP address 169.254.169.254 is a link-local address that's assigned to EC2 Instance Metadata Service (IMDS) interface. If 169.254.169.254 is excluded from the NO_PROXY list, then services that rely on IMDS will fail. For example, Boto3 will be unable to obtain temporary credentials for a role assigned to a notebook instance, resulting in the ambiguous error "Unable to locate credentials". 

To resolve this issue, add 169.254.169.254 to the NO_PROXY variables in these two locations: 
https://github.com/aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples/blob/a6b627c7de883674b3cbeefdff34947ee08aadcd/scripts/proxy-for-jupyter/on-start.sh#L21

https://github.com/aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples/blob/a6b627c7de883674b3cbeefdff34947ee08aadcd/scripts/proxy-for-jupyter/on-start.sh#L29

**Additional information:**
As described in [EC2 docs](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html) and  this [Wikipedia article](https://en.wikipedia.org/wiki/Link-local_address), Link-local IPs are only valid and accessible from the instance, so it makes no sense to forward such traffic to a proxy server. For security reasons, proxies are typically configured to drop or reject traffic destined for a link-local address, which may further confuse a person trying to troubleshoot this issue.

**Comment by dmlause** [comment]
Thank you for creating this issue. Could you raise a PR for this and test out the fix? I'd be glad to review that. If I do not hear back soon, I will close this issue for inactivity. Thank you.
