### ISSUE TITLE
How to add a custom private SSH key?

### ISSUE THREAD

**Issue by tyu0912** [aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples#70]
Hello, this isn't regarding anything existing but I was wondering if anyone knew how to add a custom private SSH key for git interactions. I tried to do the following via lifecycle configs, however, it keeps saying the authentication agent is not found. I think it has something to do with the kernels that are run for lifecycle? 

```
echo "Activating ssh agent"
eval $(ssh-agent -s)
ssh-add "${USER_HOME}/.ssh/sagemaker-bitbucket"
```

I know there's a `Git Repositories` service as part of notebooks but I think this way offers more control and also it would be easier to work with private repos. Thank you!

**Comment by mimicarina** [comment]
I experimented with this and the below worked for me. Need to run the `ssh-add` as sudo and keep environment variables set with `-e`.

```
#!/bin/bash
set -e

sudo -u ec2-user -i <<'EOF'
unset SUDO_UID
echo "Activate agent"
cd /home/ec2-user
eval `ssh-agent -s`
ssh-add /home/ec2-user/SageMaker/.ssh/id_rsa
echo "Check for key"
ps aux | grep ssh

EOF
```

**Comment by markjreed** [comment]
? "set -e" doesn't "keep environment variables set". It turns on the "errexit" (error exit) flag, which will cause the whole script to terminate immediately if any of the commands it runs signals an error. 

I don't know why you are unsetting `SUDO_UID`; `ssh-agent` doesn't have any references to that.  And SUDO_USER will still be set to the original username.

Note that `ssh-agent` is for keeping keys around in memory so (1) you can forward the agent connection for use on machines that don't have the key on their file systems, and (2) you don't have to type a passphrase every time you run an ssh command. If the key is already in a file on the instance and not passphrase protected, you don't need `ssh-agent`; just tell ssh to use that file (e.g. by putting `IdentityFile /home/ec2-user/SageMaker/.ssh/id_rsa` in /home/ec2-user/.ssh/config).

**Comment by dmlause** [comment]
Hello, @tyu0912 has this SSH issue been resolved? It has been quite some time since the latest comment, and I don't see a PR linked to this issue. If you'd like to contribute your script as a PR for this, would be glad to review it.

Otherwise if we don't hear back soon, I will close this issue. Thank you.
