### ISSUE TITLE
Autostop Cron job is recognized, but not stopping the instance. 

### ISSUE THREAD

**Issue by BanuSelinTosun** [aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples#71]
I have my Notebook setup for the run with the start. It is running my code fine. However, it does not stop the instance when the notebook is idle. For example, the code finished running 9PM last night, system recognized it. The Auto script should be shutting the instance off within 1 hour of idle; it has been ~14 hours and it is still "InService". 
Does anyone have a solution this problem?

**Comment by SanketD92** [comment]
This still happens with the new AL2 platform version. Command in lifecycle config:
```(crontab -l 2>/dev/null; echo "*/1 * * * * /usr/bin/python /usr/local/bin/autostop.py --time $IDLE_TIME --ignore-connections >> /var/log/autostop.log") | crontab -
```

Any updates on the bug fix so far?

**Comment by dmlause** [comment]
@BanuSelinTosun @SanketD92 - are you two facing this issue still? Please raise a PR with a fix if known, otherwise, please provide precise reproduction steps of the issue, so we can dive into the problem further. If I do not hear back on this issue soon, I will close it for inactivity. Thank you.

**Comment by clowtown** [comment]
@dmlause  - I have been experiencing this same issue. using the above lifecycle config on Amazon Linux 2, Jupyter Lab 3
(notebook-al2-v2), the notebook is never shutdown. I've even tried simple commands and they do not seem to be scheduled. If "Open Jupyter" and start a new shell session, `crontab -l` lists nothing, I've even gone the extra step to run crontab with `-u ec2-user` on the lifecycle start just to be sure. If I run the command from the on-start script in the shell, the crontab lists the scheduled entry and the notebook will be shutdown correctly. Seems to me like something is causing the headless session during on-start to have no effect on the overall notebook instance when interacted with.
