### ISSUE TITLE
persisting enviroment only supports python 3.7.11?

### ISSUE THREAD

**Issue by glennestonilo-TU** [aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples#80]
Followed the steps by first running the [on-create.sh and setup the on-start.sh](https://github.com/aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples/tree/master/scripts/persistent-conda-ebs) on the life cycle configuration.

changed the line on the on-create.sh
`
wget https://repo.anaconda.com/miniconda/Miniconda3-4.10.3-Linux-x86_64.sh -O "$WORKING_DIR/miniconda.sh"
KERNEL_NAME="custom_python"
PYTHON="3.6"
`

after run completion, when we run the notebook using the `custom_python` enviroment, the python version is still in 3.7.11. Any Idea what is causing this?

**Comment by MayurBMahajan** [comment]
Its because miniconda.sh gives you 3.7 and kernel you are creating is with 3.6. 
In order to get python3.6, you should point your kernel to 3.6 python which is not added as part of this git repo

**Comment by dmlause** [comment]
Closing this issue for now, please reopen the issue if a problem still exists and raise a PR if necessary, thank you.
