### ISSUE TITLE
[question] How to make a lifecycle configuration default for all new notebooks?

### ISSUE THREAD

**Issue by chopeen** [aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples#93]
Is there a way to make a certain lifecycle configuration default (ideally, also mandatory) for all new notebooks?

`auto-stop-idle` works great, but only when users do not forget to use it upon notebook creation.

I did some research but found only [studio-lcc-defaults](https://docs.aws.amazon.com/sagemaker/latest/dg/studio-lcc-defaults.html), for Studio notebooks not the classic ones.

**Comment by dmlause** [comment]
As of writing, there is no mechanism to have a default lifecycle configuration ran for a notebook instance. The lifecycle configuration needs to be passed into the create notebook instance API call. I am closing this issue for now, thank you.
